[default]
extend-ignore-re = [
  ".*(?:#|--|//|/*).*(?:spellchecker|typos):\\s?ignore[^\\n]*\\n[^\\n]*",
  ".*(?:spellchecker|typos):\\s?ignore-next-line[^\\n]*\\n[^\\n]*",
]

[default.extend-words]
# Don't correct "noice"
noice = "noice"
